# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continente', models.CharField(default='', max_length=254)),
                ('imagens', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='World',
        ),
    ]
